# poetry-bug-report
I reported this issue to https://github.com/python-poetry/poetry/issues/6733 and poetry-core==1.3.2 fixed it.

```shell
$ python -m build --version
build 0.8.0 (...)

$ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry-core==1.2.0)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry-core==1.2.0)
* Getting dependencies for wheel...
* Building wheel...
Successfully built poetry-bug-report-0.1.0.tar.gz and poetry_bug_report-0.1.0-py3-none-any.whl

$ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (poetry-core==1.3.1)
* Getting dependencies for sdist...
* Building sdist...
ERROR Source /tmp/build-via-sdist-1cju5o9a/poetry_bug_report-0.1.0 is not a directory
```
